//
// Generated by afu_json_mgr from ../../hw/bdx-rtl.json
//

#ifndef __AFU_JSON_INFO__
#define __AFU_JSON_INFO__

#define AFU_ACCEL_NAME "bdx-rtl"
#define AFU_ACCEL_UUID "23F23A41-42B4-4ACC-84CB-817BB75B35B1"
#define AFU_IMAGE_POWER 0
#define AFU_TOP_IFC "ofs_plat_afu"

#endif // __AFU_JSON_INFO__
